// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpFiXw52UwEd8Dp6if8i5dATWwuU4IuYQ',
    appId: '1:1071891098375:web:bad3370f912e28934d73a2',
    messagingSenderId: '1071891098375',
    projectId: 'shatapp-930a6',
    authDomain: 'shatapp-930a6.firebaseapp.com',
    storageBucket: 'shatapp-930a6.appspot.com',
    measurementId: 'G-TZYV0NFQLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW6m8UwhcF8H84zhwZQJ4oAAWGAHsdRx0',
    appId: '1:1071891098375:android:ec5825d64a846fec4d73a2',
    messagingSenderId: '1071891098375',
    projectId: 'shatapp-930a6',
    storageBucket: 'shatapp-930a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4NpeBcg9PsR4bwRsJbJ6I0DpmyyDPdBY',
    appId: '1:1071891098375:ios:999cf123834eda9a4d73a2',
    messagingSenderId: '1071891098375',
    projectId: 'shatapp-930a6',
    storageBucket: 'shatapp-930a6.appspot.com',
    androidClientId: '1071891098375-a535pn23aq9gr3cpisbmnri71i8n8hl7.apps.googleusercontent.com',
    iosClientId: '1071891098375-1p1eb2s9tdf8ahbouflea6nvhsmu52es.apps.googleusercontent.com',
    iosBundleId: 'com.example.shatapp',
  );
}
